# Generated by Django 5.0.2 on 2024-02-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('chain_id', models.PositiveIntegerField(unique=True)),
                ('native_currency', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
